use_frameworks!

platform :ios, '9.0'

target 'SwiftModuleA_Extension_Example' do
  pod 'SwiftModuleA_Extension', :path => '../'

  target 'SwiftModuleA_Extension_Tests' do
    inherit! :search_paths

    
  end
end
